export const themes = {
  light: {
    bg: "bg-white",
    text: "text-gray-900",
    accent: "text-blue-600",
    border: "border-gray-200",
    card: "bg-gray-50",
    headingFont: "font-poppins",
    bodyFont: "font-inter",
    headerBg: "bg-gray-100",
  },
  dark: {
    bg: "bg-gray-900",
    text: "text-white",
    accent: "text-blue-400",
    border: "border-gray-700",
    card: "bg-gray-800",
    headingFont: "font-poppins",
    bodyFont: "font-inter",
    headerBg: "bg-gray-800",
  },
  blue: {
    bg: "bg-blue-50",
    text: "text-gray-900",
    accent: "text-blue-700",
    border: "border-blue-200",
    card: "bg-white",
    headingFont: "font-poppins",
    bodyFont: "font-inter",
    headerBg: "bg-blue-100",
  },
  slateAmber: {
    bg: "bg-slate-50",
    text: "text-slate-900",
    accent: "text-amber-600",
    border: "border-slate-200",
    card: "bg-white",
    headingFont: "font-poppins",
    bodyFont: "font-inter",
    headerBg: "bg-slate-100",
  },
  slateAmberDark: {
    bg: "bg-slate-900",
    text: "text-slate-100",
    accent: "text-amber-400",
    border: "border-slate-700",
    card: "bg-slate-800",
    headingFont: "font-poppins",
    bodyFont: "font-inter",
    headerBg: "bg-slate-800",
  },
  emerald: {
    bg: "bg-emerald-50",
    text: "text-gray-900",
    accent: "text-emerald-700",
    border: "border-emerald-200",
    card: "bg-white",
    headingFont: "font-poppins",
    bodyFont: "font-inter",
    headerBg: "bg-emerald-100",
  },
  violet: {
    bg: "bg-violet-50",
    text: "text-gray-900",
    accent: "text-violet-700",
    border: "border-violet-200",
    card: "bg-white",
    headingFont: "font-poppins",
    bodyFont: "font-inter",
    headerBg: "bg-violet-100",
  },
  rose: {
    bg: "bg-rose-50",
    text: "text-gray-900",
    accent: "text-rose-700",
    border: "border-rose-200",
    card: "bg-white",
    headingFont: "font-poppins",
    bodyFont: "font-inter",
    headerBg: "bg-rose-100",
  },
};
